les_fleurs_du_mal/aplications/biblioteca/urls.py
from django.urls import path, re_path, include
from django.conf.urls import url, include

from . import views
from django.contrib.auth.views import LoginView ,PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LogoutView
from django.contrib.auth.decorators import login_required


app_name="biblioteca_app"

urlpatterns = [
    path('libros/ver', views.verlibros.as_view(), name='ver_libros'),
    path('mostrarlibro/<lb>/<v>', views.mostrarlibro.as_view(), name='mostrar_libro'),
    path('autores/<un>', views.ListaAutores.as_view(), name="lista_autores"),
    path('categorias/<un>', views.ListaCategorias.as_view(), name="lista_categorias"),
    path('editoriales/<un>', views.ListaEditoriales.as_view(), name="lista_editoriales"),
    path('revistas/<un>', views.ListaRevistas.as_view(), name="lista_revistas"),
    path('sucursales/<un>', views.ListaSucursales.as_view(), name="lista_sucursales"),
    path('servicios/<un>', views.ListaServicios.as_view(), name="lista_servicios"),
    path('reportes-Revistas/<un>', views.listaReportesLibrosAutores.as_view(), name="lista_reportesA"),
    path('reportes-Libros/<un>', views.listaReportesLibrosCategorias.as_view(), name="lista_reportesC"),
    path('reportes-Autores/<un>', views.opcionesReportesAutores.as_view(), name="opciones_reportesAutores"),
    path('reportes-Sucursales/<un>', views.opcionesReportesSucursales.as_view(), name="opciones_reportesSucursales"),
    re_path('z',views.lista.as_view(), name="veamos"),
    path('categoria/add/<un>', views.addCategoria.as_view(),name="agregar_categoria"),
    path('reporte/libro-categoria/<pk>/',views.CantidadCategoria_libros.as_view(),name="CantidadLibros-categoria"),
    path('reporte/revista-categoria/<pk>/', views.CantidadCategoria_revistas.as_view(), name="CantidadLibros-categoria"),
    path('reporte/libro-autor/<pk>/',views.CantidadAutor_libros_pdf.as_view(), name="CantidadLibros-autor"),
    path('reporte/sucursal-libro/<pk>/',views.CantidadSucursal_libros.as_view(), name="CantidadLibros-sucursal"),
    path('reporte/autor-libro/<pk>/',views.reporteAutoresLibro.as_view(), name="ReporteAutor_libro"),
    path('reporte/autor-nacionalidad/<pk>/',views.CantidadAutor_nacionalidad_pdf.as_view(), name="ReporteAutor_nacionalidad"),
    path('editorial/add/<un>', views.addEditorial.as_view(), name="agregar_editorial"),
    path('revista/add/<un>', views.addRevista.as_view(), name="agregar_revista"),
    path('sucursal/add/<un>', views.addSucursal.as_view(), name="agregar_sucursal"),
    path('servicio/add/<un>',views.addServicio.as_view(),name="agregar_servicio"),
    path('registro/<ca>/<us>',views.addUsuarioAdmin.as_view(), name="registro"),
    path('codigo/<ca>/<us>', views.addCodigoAdmin.as_view(), name='codigoAdmin'),
    path('editar-autor/<pk>/<un>', views.editAutor.as_view(), name="editar_autor"),
    path('editar-categoria/<pk>/<un>', views.editCategoria.as_view(), name="editar_categoria"),
    path('editar-editorial/<pk>/<un>', views.editEditorial.as_view(), name="editar_editorial"),
    path('editar-revista/<pk>/<un>', views.editRevista.as_view(), name="editar_revista"),
    path('editar-sucursal/<pk>/<un>',views.editSucursal.as_view(), name="editar_sucursal"),
    path('editar-servicio/<pk>/<un>', views.editServicio.as_view(), name="editar_servicio"),
    path('eliminar-autor/<pk>/<un>', views.deleteAutor.as_view(), name="eliminar_autor"),
    path('eliminar-libro/<pk>/<un>', views.deleteLibro.as_view(), name="eliminar_libro"),
    path('eliminar-categoria/<pk>/<un>', views.deleteCategoria.as_view(), name="eliminar_categoria"),
    path('eliminar-editorial/<pk>/<un>', views.deleteEditorial.as_view(), name="eliminar_editorial"),
    path('eliminar-revista/<pk>/<un>', views.deleteRevista.as_view(), name="eliminar_revista"),
    path('eliminar-sucursal/<pk>/<un>', views.deleteSucursal.as_view(), name="eliminar_sucursal"),
    path('eliminar-servicio/<pk>/<un>', views.deleteServicio.as_view(), name="eliminar_servicio"),
    path('editar-libro/<pk>/<un>', views.editLibro.as_view(), name="editar_libro"),
    path('buscar-libro/<pk>/<un>', views.buscarLibro.as_view(), name="buscar_libro"),
    path('buscar-editorial/<pk>/<un>', views.buscarEditorial.as_view(), name="buscar_editorial"),
    path('buscar-autor/<pk>/<un>', views.buscarAutor.as_view(), name="buscar_autor"),
    path('buscar-categoria/<pk>/<un>', views.buscarCategoria.as_view(), name="buscar_categoria"),
    path('buscar-revista/<pk>/<un>', views.buscarRevista.as_view(), name="buscar_revista"),
    path('buscar-sucursal/<pk>/<un>', views.buscarSucursal.as_view(), name="buscar_sucursal"),
    path('buscar-servicio/<pk>/<un>', views.buscarServicio.as_view(), name="buscar_servicio"),
    path('reporte/libros/<pk>/<fk>', views.rangoflibros.as_view(), name="filtrar_libros"),
    path('reporte/revistas/<pk>/<fk>', views.rangofrevistas.as_view(), name="filtrar_libros"),
    path('libros/<un>', views.ListaLibros.as_view(), name="lista_libros"),
    path('autor/add/<un>', views.addAutor.as_view(), name="Agregar_autores"),
    path('libro/add/<un>', views.addLibro.as_view(), name="Agregar_libros"),
    re_path('js', views.script.as_view(), name="js"),

    path('admin/<ca>', views.registro.as_view(), name="sd"),
    path('admin', views.ErrorUrlAdmin.as_view(), name="ErrorAdminSinCA"),
    path('admin/', views.ErrorUrlAdmin.as_view(), name="ErrorAd"),

    path('<ca>/er', views.errorsesion.as_view(), name="errorsesion"),
    path('er2/<cs>/', views.errorsesion2.as_view(), name="er2"),
    path('inicioA/<un>', views.Inicio.as_view(), name="index"),

    path('', views.inicioLogin.as_view(), name='inicioLogin'),

    path('errorLogin', views.errorLogin.as_view(), name="errorLogin"),
    path('login/add', views.addLogin.as_view(), name="addLogin"),
    path('inicioS/<us>', views.sesionLogin.as_view(), name='sesionLogin'),
    path('descripcionLibro/<lb>/<us>', views.descripcionLibro.as_view(), name='descripcion_libro'),
    path('comentar',views.comentar.as_view(), name='comentar'),
    path('Logout/<us>', views.cerarSesionLogin.as_view(), name='Logout'),
    path('fav',views.fav.as_view(), name='Fav'),
    path('saldo/<us>', views.saldo.as_view(), name='saldo'),
    path('agregarSaldo', views.addSaldo.as_view(), name='addSaldo'),
    path('comprar', views.comprar.as_view(), name='comprar'),
    path('MiBiblioteca/<us>', views.BibliotecaCompras.as_view(), name='MiBiblioteca'),
    path('enviarEmail/<us>', views.EnviarEmail.as_view(), name='enviarEmail'),
    path('ajax/validarAdmin', views.validate_userAdmin, name="Validar_Inicio_Admin"),
    path('inicioAdmin', views.inicioAdmin, name="inicio_admin"),
    #Falta agregar descripcion sin login


]

les_fleurs_du_mal/les_fleurs_du_mal/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views



urlpatterns = [

   
    path('', include('aplications.biblioteca.urls')),


]

les_fleurs_du_mal/templates/base/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    {% block head %}
    <script src="{% static 'js/calis.js' %}"></script>
    {% endblock %}
</head>
{% block body %}<body onload="calis()">{% endblock %}
{% block contenido %}
{% endblock %}



<input type="hidden" id="usuariot" value="{{a.username}}">
<input type="hidden" id="usuario">
</body>
</html>

les_fleurs_du_mal/templates/base/baseAgregar.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block headAdd %}
        <meta charset="UTF-8">
        <title>Les fleurs du mal</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/agregar.css'%}">

        {% endblock %}
        {% block script%}<script src="{% static 'js/agregar.js' %}"></script>
        <script src="{% static 'js/url.js' %}" ></script>
        {% endblock %}

    </head>
    {% block bodyAdd %}
    <body  onload="cambiarValores()" background="{% static '275.jpg'%}">{% endblock %}
        <nav class="navbar navbar-dark bg-dark">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>



            <h1	style="color:white">AGREGAR {%block agregar%}AUTOR{%endblock%}</h1>
            <form class="form-inline" id="formulario" action="#" onsubmit="return buscarautor()" autocomplete="off">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" id="buscar">
                <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
            </form>

            {%block nav%}<div class="navbar-collapse collapse" id="navbarColor01" style="">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="javascript:pasarUsuario('/inicioA/','ni')">Inicio <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">

                        <div class="btn-group dropright">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="btnUsuario">
                            </button>
                            <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a href="/f/" id="cierre de sesion">Cerrar Sesion</a>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">

                    <div class="btn-group dropright">
                        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Libros
                        </button>
                        <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                            <a class="dropdown-item" href="javascript:pasarUsuario('/libros/','ni')">Ver</a>
                            <a class="dropdown-item" href="javascript:pasarUsuario('/libro/add/','ni')">Agregar</a>
                        </div>
                    </div>
                    </li>
                    <li class="nav-item">
                        <div class="btn-group dropright">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Autores
                            </button>
                            <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="javascript:pasarUsuario('/autores/','ni')">Ver</a>
                                <a class="dropdown-item" href="javascript:pasarUsuario('/autor/add/','ni')">Agregar</a>
                            </div>
                        </div>
                    </li>
                <li class="nav-item">

                    <div class="btn-group dropright">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categorias
                            </button>
                            <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="javascript:pasarUsuario('/categorias/','ni')">Ver</a>
                                <a class="dropdown-item" href="javascript:pasarUsuario('/categoria/add/','ni')">Agregar</a>
                            </div>
                        </div>
                </li>
                    <li class="nav-item">

                        <div class="btn-group dropright">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Editoriales
                            </button>
                            <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="javascript:pasarUsuario('/editoriales/','ni')">Ver</a>
                                <a class="dropdown-item" href="javascript:pasarUsuario('/editorial/add/','ni')">Agregar</a>
                            </div>
                        </div>
                </li>
                    <li class="nav-item">

                        <div class="btn-group dropright">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Revistas
                            </button>
                            <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="javascript:pasarUsuario('/revistas/','ni')">Ver</a>
                                <a class="dropdown-item" href="javascript:pasarUsuario('/revista/add/','ni')">Agregar</a>
                            </div>
                        </div>
                </li>
                    <li class="nav-item">
                        <div class="btn-group dropright">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Sucursales
                            </button>
                            <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="javascript:pasarUsuario('/sucursales/','ni')">Ver</a>
                                <a class="dropdown-item" href="javascript:pasarUsuario('/sucursal/add/','ni')">Agregar</a>
                            </div>
                        </div>
                </li>
                    <li class="nav-item">
                        <div class="btn-group dropright">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Servicios
                            </button>
                            <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="javascript:pasarUsuario('/servicios/','ni')">Ver</a>
                                <a class="dropdown-item" href="javascript:pasarUsuario('/servicio/add/','ni')">Agregar</a>
                            </div>
                        </div>
                </li>
                    <li class="nav-item">
                        <div class="btn-group dropright">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Reportes
                            </button>
                            <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="javascript:pasarUsuario('/reportes-Libros/','ni')">Libros</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/reportes-Revistas/','ni')">Revistas</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/reportes-Autores/','ni')">Autores</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/reportes-Sucursales/','ni')">Sucursales</a>
                            </div>
                        </div>
                    </li>

                </ul>

            </div>{%endblock%}

            </nav>
<div id="AgregarContenido">
        {% block tituloAdd %}




        <!--<h1 ><a href="javascript:history.back(-1);" id="menu">Regresar</a>{% block textoAdd %}Agregar Libro{% endblock %} </h1>-->
        {% endblock%}

            <form method="post" id="agregar" autocomplete="off">{% csrf_token %}
                {{ form.as_p}}
                <button type="submit" name="button" class="btn btn-primary" id="btnAgregar" {% block onclick %} onclick="lowerT()" {% endblock %}>Guardar</button>
                {%block errorUsuarioAdmin%}
                {%endblock%}

            </form>

        <script>
            var ni = carga();
        </script>

        {% block alerta%}

        {%endblock%}

</div>
        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
            <script src="{% static 'js/popper.min.js'%}"></script>
            <script src="{% static 'js/bootstrap.min.js'%}"></script>
    {%block ajax%}
    {%endblock%}
    </body>

</html>

les_fleurs_du_mal/templates/base/baseEliminar.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Les fleurs du mal</title>
    {% block link %}<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">{% endblock %}


	<script src="{% static 'js/eliminar.js'%}"></script>

</head>
{% block body %}<body onload="eliminar()">{% endblock %}


<h1>Agregar Autor</h1>

	<form method="post">{% csrf_token %}
		{{ form.as_p}}
		<button type="submit" name="button" class="btn btn-primary" id="borrar">Guardar</button>

	</form>
</body>
</html>

les_fleurs_du_mal/templates/base/baseLista.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Les fleurs du mal</title>
    {% block link %}<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tabla.css'%}">{% endblock %}
    {% block script %}
    <script src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
    <script src="{% static 'js/buscar.js'%}"></script>
    <script src="{% static 'js/url.js'%}"></script>

    {% endblock %}
</head>

{% block body %}<body background="{% static '275.jpg'%}" onload="link()">{% endblock%}

<nav class="navbar navbar-dark bg-dark">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>



    <h1 style="color:white">{% block tituloNav %}BIENVENIDO{% endblock %}</h1>


     {% block formBuscar %}<form class="form-inline" id="formulario" action="#" onsubmit="return buscarNombre('autor')" autocomplete="off">{% endblock %}
      <input class="form-control mr-sm-2" type="text" placeholder="Search" id="buscar">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>

      <div class="navbar-collapse collapse" id="navbarColor01" style="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="javascript:pasarUsuario('/inicioA/','ni')">Inicio <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">

          <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="btnUsuario">

                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                   <a href="/f/" id="cierre de sesion">Cerrar Sesion</a>

                </div>
            </div>
      </li>
      <li class="nav-item">

          <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Libros
                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="javascript:pasarUsuario('/libros/','ni')">Ver</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/libro/add/','ni')">Agregar</a>
                </div>
            </div>
      </li>
      <li class="nav-item">
          <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Autores
                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="javascript:pasarUsuario('/autores/','ni')">Ver</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/autor/add/','ni')">Agregar</a>
                </div>
            </div>
      </li>
      <li class="nav-item">

          <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Categorias
                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="javascript:pasarUsuario('/categorias/','ni')">Ver</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/categoria/add/','ni')">Agregar</a>
                </div>
            </div>
      </li>
        <li class="nav-item">

            <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Editoriales
                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="javascript:pasarUsuario('/editoriales/','ni')">Ver</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/editorial/add/','ni')">Agregar</a>
                </div>
            </div>
      </li>
        <li class="nav-item">

            <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Revistas
                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="javascript:pasarUsuario('/revistas/','ni')">Ver</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/revista/add/','ni')">Agregar</a>
                </div>
            </div>
      </li>
        <li class="nav-item">
            <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sucursales
                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="javascript:pasarUsuario('/sucursales/','ni')">Ver</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/sucursal/add/','ni')">Agregar</a>
                </div>
            </div>
      </li>
        <li class="nav-item">
            <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Servicios
                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="javascript:pasarUsuario('/servicios/','ni')">Ver</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/servicio/add/','ni')">Agregar</a>
                </div>
            </div>
      </li>
        <li class="nav-item">
            <div class="btn-group dropright">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Reportes
                </button>
                <div class="dropdown-menu" x-placement="right-start" style="position: absolute; transform: translate3d(111px, 0px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <a class="dropdown-item" href="javascript:pasarUsuario('/reportes-Libros/','ni')">Libros</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/reportes-Revistas/','ni')">Revistas</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/reportes-Autores/','ni')">Autores</a>
                    <a class="dropdown-item" href="javascript:pasarUsuario('/reportes-Sucursales/','ni')">Sucursales</a>
                </div>
            </div>
        </li>

    </ul>

  </div>

    </nav>

<div id="ListaContenido">
<input type="hidden" id="usuario" value="{{a.username}}">

{% if l %}
<div id="tabla">
<table border="2" width="1920" class="rounded-sm" bgcolor="white">
   {% block thead %} <thead>
    <th>Nombre</th>
    <th>Apellidos</th>
    <th>Nacionalidad</th>
    <th>Fecha de Creacion</th>
    <th>Fecha de modificacion</th>
    <th>Eliminar</th>
    <th>Editar</th>
    </thead>
    {% endblock %}
    <tbody>

    {% for a in l %}

				{% block tr %}
                <tr>
					<td>
						{{a.nombre_autor.capitalize}}
					</td>
					<td>
						{{a.apellidos_autor.capitalize}}
					</td>
                    <td>{{a.nacionalidad_autor.capitalize}}
                    </td>
                    <td>
                       {{a.fecha_creacion_autor}}

                    </td>
                    <td>{{a.fecha_modificacion_autor}}
                    </td>
					<td>
                        <a class="btn btn-danger" href="{%url 'biblioteca_app:eliminar_autor' a.id_autor%}">Eliminar</a>
					</td>
                    <td>
                        <a href="{%url 'biblioteca_app:editar_autor' a.id_autor%}" class="btn btn-info" >Editar</a>
                    </td>
				</tr>
                {% endblock%}

    {%endfor%}



    </tbody>
</table>


</div>

<a href="/libros/ver"><button>VER LIBROS</button></a>
{% else %}
        <h1 style="background-color:white">{% block nohay %}NO HAY LIBROS{% endblock %}</h1>
<button onclick="carga()">Usuario</button>
{% endif %}
<script>
    var ni = carga();
</script>
{%block corr%}
{%endblock%}
</div>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
<a href="/">a ver si lleva al inicio</a>
</body>
</html>